# Site settings
title: Developer Blogs
# description: Blog from Sajan Basnet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://developerblogs.github.io/"
disqus_shortname: developerblogs
tag_url: 'https://developerblogs.github.io/blogs/'


# User settings
username: Sajan Basnet
user_description: Forward-thinking software engineering professional with organized nature, good critical thinking skills and kind of a introvert. Currently working as a <strong> Ruby on Rails </strong> developer at <a  style="text-decoration:none" href="https://www.gurzu.com" target="_blank"><b> Gurzu Inc </b></a>
user_title: Software Engineer
email: sajanbasnet75@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-172425420-1"

exclude: ['package.json', 'src' , 'node_modules']

baseurl: ""

paginate: 6
paginate_path: "/blogs/page/:num/"

markdown: kramdown
kramdown:
  parse_block_html: true
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
syntax_highlighter_opts:
  css_class: 'codehilite'
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-debug
  - jemoji
  - jekyll-feed
